import MarkdownRenderer from "../chat/MarkdownRenderer";
import type { Conversation } from "../../types/conversation";

interface Props {
  conversation: Conversation | null;
}

const ExportDocument = ({ conversation }: Props) => {
  if (!conversation) return null;

  return (
    <div
      style={{
        width: "210mm",
        minHeight: "297mm",
        background: "#ffffff",
        color: "#111827",
        padding: "45px",
        fontFamily:
          "Inter, Segoe UI, Arial, Helvetica, sans-serif",
        lineHeight: 1.7,
      }}
    >
      {/* Header */}

      <div
        style={{
          borderBottom: "3px solid #2563eb",
          paddingBottom: 18,
          marginBottom: 40,
        }}
      >
        <h1
          style={{
            margin: 0,
            fontSize: 34,
            fontWeight: 800,
            color: "#111827",
          }}
        >
          {conversation.title}
        </h1>

        <p
          style={{
            marginTop: 10,
            color: "#6b7280",
            fontSize: 14,
          }}
        >
          Generated by <strong>Flux AI</strong>

          <br />

          {new Date().toLocaleString()}
        </p>
      </div>

      {/* Conversation */}

      {conversation.messages.map((message, index) => (
        <section
          key={message.id}
          style={{
            marginBottom: 35,
            pageBreakInside: "avoid",
          }}
        >
          {/* Role */}

          <div
            style={{
              display: "flex",
              alignItems: "center",
              marginBottom: 14,
            }}
          >
            <div
              style={{
                width: 42,
                height: 42,
                borderRadius: "50%",
                background:
                  message.role === "user"
                    ? "#2563eb"
                    : "#10b981",

                color: "white",

                display: "flex",
                alignItems: "center",
                justifyContent: "center",

                fontWeight: 700,
                fontSize: 18,
              }}
            >
              {message.role === "user" ? "Y" : "F"}
            </div>

            <div
              style={{
                marginLeft: 12,
              }}
            >
              <div
                style={{
                  fontWeight: 700,
                  fontSize: 17,
                }}
              >
                {message.role === "user"
                  ? "You"
                  : "Flux AI"}
              </div>

              <div
                style={{
                  fontSize: 12,
                  color: "#6b7280",
                }}
              >
                Message {index + 1}
              </div>
            </div>
          </div>

          {/* Bubble */}

          <div
            style={{
              background:
                message.role === "user"
                  ? "#eff6ff"
                  : "#ffffff",

              border:
                message.role === "user"
                  ? "1px solid #bfdbfe"
                  : "1px solid #e5e7eb",

              borderRadius: 16,

              padding: 22,

              overflowWrap: "break-word",
            }}
          >
            {message.attachments?.length ? (
              <div
                style={{
                  marginBottom: 18,
                  padding: 12,
                  background: "#f9fafb",
                  border: "1px solid #e5e7eb",
                  borderRadius: 10,
                  fontSize: 13,
                }}
              >
                <strong>Attachments</strong>

                <ul
                  style={{
                    marginTop: 8,
                    marginBottom: 0,
                  }}
                >
                  {message.attachments.map((file) => (
                    <li key={file.id}>
                      {file.filename}
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}

            <MarkdownRenderer
              content={message.content}
            />
          </div>
        </section>
      ))}

      {/* Footer */}

      <div
        style={{
          marginTop: 60,
          borderTop: "1px solid #e5e7eb",
          paddingTop: 18,
          textAlign: "center",
          color: "#6b7280",
          fontSize: 12,
        }}
      >
        Export generated using Flux AI
      </div>
    </div>
  );
};

export default ExportDocument;